# 
#  .zshrc
#  
#  Created by Omer Jakobinsky.
# 

. ~/.dotfiles/zsh/aliases
. ~/.dotfiles/zsh/config
. ~/.dotfiles/zsh/functions

if [[ -s /Users/omer/.rvm/scripts/rvm ]] ; then source /Users/omer/.rvm/scripts/rvm ; fi
